# Generated by Django 5.2.15 on 2026-06-23 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=180)),
                ("organizer", models.CharField(blank=True, max_length=160)),
                ("event_date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=140)),
                ("description", models.TextField(blank=True)),
                ("event_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ("-event_date", "order"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("qualification", models.CharField(max_length=180)),
                ("institution", models.CharField(max_length=180)),
                ("field_of_study", models.CharField(blank=True, max_length=180)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Education",
                "ordering": ("-end_date", "-start_date", "order"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("job_title", models.CharField(max_length=160)),
                ("organization", models.CharField(max_length=180)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Use a new line for each achievement or responsibility.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work experience",
                "verbose_name_plural": "Work experience",
                "ordering": ("-start_date", "order"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(default="Ibrahim Mrisha", max_length=120),
                ),
                (
                    "professional_title",
                    models.CharField(default="FullStack Developer", max_length=160),
                ),
                ("location", models.CharField(default="Tanzania", max_length=120)),
                (
                    "organization",
                    models.CharField(blank=True, default="Technology", max_length=160),
                ),
                (
                    "email",
                    models.EmailField(
                        default="ibrahim.mrisha@yahoo.com", max_length=254
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("website", models.URLField(blank=True)),
                (
                    "github_url",
                    models.URLField(
                        blank=True, default="https://github.com/mrishason/"
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        default="https://www.linkedin.com/in/mr-mrisha-754436155/",
                    ),
                ),
                ("profile_photo", models.ImageField(blank=True, upload_to="profile/")),
                (
                    "short_bio",
                    models.TextField(
                        default="I am a passionate FullStack Developer and technology enthusiast focused on creating useful, reliable, and human-centered digital experiences."
                    ),
                ),
                (
                    "about_paragraph_1",
                    models.TextField(
                        blank=True,
                        default="My work combines thoughtful design with practical engineering. From responsive websites and modern applications to scalable systems, I approach every project with curiosity, attention to detail, and a commitment to continuous improvement.",
                    ),
                ),
                (
                    "about_paragraph_2",
                    models.TextField(
                        blank=True,
                        default="Beyond writing code, I value collaboration and knowledge sharing. I am always interested in meeting other builders, exploring new ideas, and contributing to technology communities that create meaningful opportunities.",
                    ),
                ),
                (
                    "about_paragraph_3",
                    models.TextField(
                        blank=True,
                        default="I am open to new challenges and collaborations. Let's connect and build something thoughtful together.",
                    ),
                ),
                (
                    "cv_summary",
                    models.TextField(
                        blank=True,
                        help_text="Professional summary displayed at the top of the generated CV.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profile & CV contact details",
                "verbose_name_plural": "Profile & CV contact details",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=160)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField()),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Example: Django, PostgreSQL, JavaScript",
                        max_length=240,
                    ),
                ),
                ("project_url", models.URLField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="projects/")),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-featured", "order", "-id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("publisher", models.CharField(blank=True, max_length=160)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                ("publication_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ("-publication_date", "order"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("tool", "Tools & platforms"),
                            ("language", "Languages"),
                            ("soft", "Professional"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveSmallIntegerField(
                        default=80,
                        help_text="A value from 1 to 100.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("order", "-id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ("order", "-id"),
                "abstract": False,
            },
        ),
    ]
