# Generated by Django 5.2.15 on 2026-06-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_seed_initial_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ("category", "order", "name")},
        ),
    ]
